verbose: True # Whether to print info
max_episode_length: 50 # maximum iteration length of an episode
entity_name: 'forklift_bot' # entity name of the forklift robot in the simulation
ros_controller_names:  ['joint_broad', 'fork_joint_controller', 'diff_cont'] # ROS2 controllers that are activated.
tolerance_x: 1.115 # chassis_bottom_transform's x location's tolerable distance to target_location's x coordinate for agent to achieve the goal state
tolerance_y: 1.59  # chassis_bottom_transform's y location's tolerable distance to target_location's y coordinate for agent to achieve the goal state
agent_pose_position_z: 0.30 # agent's z coordinate when spawned in the world
world_file_name: 'road.world' # specifies world used for gazebo simulation. These worlds are available in /world folder.
observation_type: "tf_only" # specifies the observation space used. Check out ObservationType Enum inside utils.py for available options.
reward_type: "L2_distance" # specifies the reward function being used. Check out RewardType Enum inside utils.py for available options.
action_type: "differential_control" # specifies the actions that will be taken by the agent. Check out ActionType Enum inside utils.py for available options.
