ForkliftBot:
  # Publish all joint states -----------------------------------
  # joint_state_controller:
  #   type: joint_state_controller/JointStateController
  #   publish_rate: 50
  ros__parameters:
    update_rate: 50 # Hz

  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_wheel_joint
    pid: { p: 100.0, i: 0.01, d: 10.0 }

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_wheel_joint"
    pid: { p: 100.0, i: 0.01, d: 10.0 }
