controller_manager:
  ros__parameters:
    update_rate: 50 #Hz
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    fork_joint_controller:
      # type: effort_controllers/JointGroupEffortController" # refer to https://github.com/ros-controls/ros2_controllers/blob/master/effort_controllers/effort_controllers_plugins.xml
      type: forward_command_controller/ForwardCommandController # refer to https://github.com/ros-controls/ros2_controllers/blob/master/diff_drive_controller/diff_drive_plugin.xml
      # type: joint_trajectory_controller/JointTrajectoryController

fork_joint_controller: # refer to https://github.com/ros-controls/ros2_controllers/blob/master/forward_command_controller/src/forward_command_controller_parameters.yaml
  ros__parameters:
    joints:
      - fork_base_joint
    interface_name: position # available options are as follows [effort, position, velocity]
    # interface_name: velocity
    # write_op_modes:
    #   - fork_base_joint
    # command_interfaces:
    #   - effort
    # state_interfaces:
    #   - position

diff_cont: # refer to https://github.com/ros-controls/ros2_controllers/blob/master/diff_drive_controller/src/diff_drive_controller_parameter.yaml
  ros__parameters:
    publish_rate: 50.0 #50 Hz

    base_frame_id: chassis_bottom_link #TODO: this was base_link NOT SURE IF I SET IT CORRECTLY !

    right_wheel_names: [right_front_wheel_joint]
    left_wheel_names: [left_front_wheel_joint]
    wheel_separation: 0.655
    wheel_radius: 0.30

    use_stamped_vel: false

    # Check out for more info on available parameters: https://github.com/ros-controls/ros2_controllers/blob/master/diff_drive_controller/src/diff_drive_controller_parameter.yaml

    # open_loop: false

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN
# joint_broad:
#   ros__parameters:
